# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('visible_name', models.CharField(max_length=50)),
                ('needs_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField()),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('page', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='app.Report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportInputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField()),
                ('can_be_empty', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesInputModel',
            fields=[
                ('reportinputmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ReportInputModel')),
                ('choices', models.ManyToManyField(related_name='dk_2', to='app.ChoiceModel')),
                ('default_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dk_1', to='app.ChoiceModel')),
            ],
            bases=('app.reportinputmodel',),
        ),
        migrations.CreateModel(
            name='DateInputModel',
            fields=[
                ('reportinputmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ReportInputModel')),
                ('default_date', models.DateTimeField()),
            ],
            bases=('app.reportinputmodel',),
        ),
        migrations.CreateModel(
            name='RangeInputModel',
            fields=[
                ('reportinputmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ReportInputModel')),
                ('default_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
            ],
            bases=('app.reportinputmodel',),
        ),
        migrations.CreateModel(
            name='TextInputModel',
            fields=[
                ('reportinputmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ReportInputModel')),
                ('default_text', models.CharField(max_length=255)),
            ],
            bases=('app.reportinputmodel',),
        ),
        migrations.AddField(
            model_name='reportinputmodel',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='app.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='app.Report'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
