# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160918_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureInputModel',
            fields=[
                ('reportinputmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ReportInputModel')),
            ],
            bases=('app.reportinputmodel',),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Admin'), (1, 'Driver')], default=1),
        ),
        migrations.AddField(
            model_name='reportinputmodel',
            name='placeholder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='choicemodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dateinputmodel',
            name='default_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rangeinputmodel',
            name='default_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rangeinputmodel',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rangeinputmodel',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportinputmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportinputmodel',
            name='page_order',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reportresult',
            name='uploaded_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reportresultinput',
            name='choice_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dk_3', to='app.ChoiceModel'),
        ),
        migrations.AlterField(
            model_name='reportresultinput',
            name='date_value',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportresultinput',
            name='range_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportresultinput',
            name='signature_value',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reportresultinput',
            name='text_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='textinputmodel',
            name='default_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
