# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160919_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_image', models.FileField(upload_to='')),
                ('bus_id', models.CharField(max_length=25)),
                ('plate_number', models.CharField(max_length=7)),
                ('motor_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BusService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('service_date', models.DateField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bus')),
            ],
        ),
        migrations.AddField(
            model_name='signatureinputmodel',
            name='default_typed_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='choicesinputmodel',
            name='default_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dk_1', to='app.ChoiceModel'),
        ),
    ]
