# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160927_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Horvát Jenő', max_length=255),
            preserve_default=False,
        ),
    ]
