# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160930_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(default='This is a new page', max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='New Page', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, default='This is a new report', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(default='New Report', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportinputgroupmodel',
            name='description',
            field=models.CharField(blank=True, default='This is a new input group', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportinputgroupmodel',
            name='title',
            field=models.CharField(default='New Group', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportinputmodel',
            name='description',
            field=models.CharField(blank=True, default='This is a new input field', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportinputmodel',
            name='title',
            field=models.CharField(default='New Input', max_length=50),
        ),
    ]
