# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161002_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.SmallIntegerField(default=1),
        ),
    ]
