# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 10:41
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161002_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDriver',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Profile')),
            ],
            bases=('app.profile',),
        ),
        migrations.CreateModel(
            name='ChoiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.user_comment_path)),
                ('timestamp', models.DateTimeField()),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, default='This is a new report', max_length=255, null=True)),
                ('document', models.FileField(max_length=255, upload_to=app.models.user_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='choicemodel',
            name='visible_name',
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='is_bad_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rangeinputmodel',
            name='increment',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='needs_bus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='needs_user_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportresultinput',
            name='signature_typed_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_image',
            field=models.FileField(upload_to=app.models.bus_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='choicemodel',
            name='name',
            field=models.CharField(default='Choice 1', max_length=25),
        ),
        migrations.RemoveField(
            model_name='choicesinputmodel',
            name='choices',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Admin'), (1, 'Driver'), (2, 'Co-Worker')], default=1),
        ),
        migrations.AlterField(
            model_name='reportinputgroupmodel',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app.Page'),
        ),
        migrations.AlterField(
            model_name='reportinputmodel',
            name='input_type',
            field=models.SmallIntegerField(choices=[(0, 'Text'), (1, 'Date'), (2, 'Slider'), (3, 'Choices'), (4, 'Signature')], default=3),
        ),
        migrations.AlterField(
            model_name='reportinputmodel',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='app.Page'),
        ),
        migrations.AlterField(
            model_name='reportresultinput',
            name='signature_value',
            field=models.FileField(blank=True, null=True, upload_to=app.models.user_signature_path),
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AddField(
            model_name='commentfileupload',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AddField(
            model_name='busdriver',
            name='bus_driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_1', to='app.FileData'),
        ),
        migrations.AddField(
            model_name='busdriver',
            name='digital_tachograph_card_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_4', to='app.FileData'),
        ),
        migrations.AddField(
            model_name='busdriver',
            name='driving_licence_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_2', to='app.FileData'),
        ),
        migrations.AddField(
            model_name='busdriver',
            name='jobcontract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_6', to='app.FileData'),
        ),
        migrations.AddField(
            model_name='busdriver',
            name='medical_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_5', to='app.FileData'),
        ),
        migrations.AddField(
            model_name='busdriver',
            name='paf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_7', to='app.FileData'),
        ),
        migrations.AddField(
            model_name='busdriver',
            name='passport_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_3', to='app.FileData'),
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ChoiceGroup'),
        ),
        migrations.AddField(
            model_name='choicesinputmodel',
            name='choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ChoiceGroup'),
        ),
    ]
