# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20161015_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateinputmodel',
            name='default_date_expression',
            field=models.CharField(blank=True, choices=[('Today', 'Today')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='app.Report'),
        ),
        migrations.AlterField(
            model_name='rangeinputmodel',
            name='default_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rangeinputmodel',
            name='increment',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rangeinputmodel',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rangeinputmodel',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportinputmodel',
            name='input_type',
            field=models.SmallIntegerField(choices=[(3, 'Choices'), (1, 'Date'), (2, 'Slider'), (0, 'Text'), (4, 'Signature')], default=3),
        ),
    ]
