# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20161016_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicesinputmodel',
            name='choices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ChoiceGroup'),
        ),
    ]
