# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20161016_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicesinputmodel',
            name='default_choice',
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='is_default_answer',
            field=models.BooleanField(default=False),
        ),
    ]
