# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20161016_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodel',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app.ChoiceGroup'),
        ),
    ]
